#./run.sh "a sleek solarpunk spaceship in the style of the millenium falcon but nicer" "spaceship"
#./run.sh "a cute little robot picking a flower" "robot"
#./run.sh "a sleek and clean futuristic spaceship inspired by the optimism of star trek" "spaceship"
#./run.sh "a sleek, futuristic, and luxurious starship inspired by the optimism of star trek" "starship"
#./run.sh "A sleek, futuristic, and luxurious starship inspired by the optimism of star trek, it has a visible cockpit and several windows on each side allowing crew inside to view the stars. It should have an aerodynamic hull, resembling a modern yacht or oceanic vessel. The view should be zoomed out enough to fit the whole starship in the frame." "starship"
#./run.sh "A very cool steampunk flying air ship crewed by pirates, with wooden and brass fairings, propellers and sails, reminicent of classic clipper ships and also derrigible airships" "ship"
#./run.sh "A flying steampunk ship, like a pirate ship or very large fortress in the sky, crewed by pirates, made mostly of wood, with some steel and brass fairings, and propellers" "ship"
#./run.sh "A flying steampunk airship, powered by steam engines, reminiscent of zeppelin or derrigible, but with large hanging deck below with many windows, made mostly of wood with some steel and brass fairings. It resembles a large aircraft with propellers, and steam engines and vents" "steampunk"
#./run.sh "A large steampunk propeller airplane, powered by steam engines, with an open deck on top, made mostly of wood with some steel and brass fairings" "steampunk"
#./run.sh "A steampunk tavern with brass boilers and brick walls, like a western saloon" "tavern"
#./run.sh "A steampunk tavern, like a bar or pub, or a western saloon, from a fantasy town where everything is steampunk and made of wood and brass" "tavern"
#./run.sh "A steampunk bank tower, with a fortress like vault, in a fantasy steampunk city" "tower"
./run.sh "A large steampunk flying airship, aircraft carrier, zeppelin, blimp, airplane, flying fortress, steampunk pirates aircraft, full view, zoomed out, high res" "aircraft"
#c1ac4244fc9f3edbbd4ad48774f2e9fef5b382e8c0c068e8fe49279ceee1fccb  ./point_e_model_cache/ViT-L-14.pt